version: '3'
services:
  discount:
    build:
      context: .
      dockerfile: discount.Dockerfile
    ports:
      - 11443:11443
  products_listing:
    build:
      context: .
      dockerfile: products_listing.Dockerfile
    environment:
      - DISCOUNT_SERVICE_HOST=discount:11443
    links: 
      - discount:discount
    depends_on:
      - discount
    ports:
      - 11080:11080