// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashtest.proto

package hashtest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int32          `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *DiscountValue `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa949c85a716cb, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetDiscount() *DiscountValue {
	if m != nil {
		return m.Discount
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa949c85a716cb, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

type DiscountValue struct {
	Pct                  float32  `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	ValueInCents         int32    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountValue) Reset()         { *m = DiscountValue{} }
func (m *DiscountValue) String() string { return proto.CompactTextString(m) }
func (*DiscountValue) ProtoMessage()    {}
func (*DiscountValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa949c85a716cb, []int{2}
}

func (m *DiscountValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountValue.Unmarshal(m, b)
}
func (m *DiscountValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountValue.Marshal(b, m, deterministic)
}
func (m *DiscountValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountValue.Merge(m, src)
}
func (m *DiscountValue) XXX_Size() int {
	return xxx_messageInfo_DiscountValue.Size(m)
}
func (m *DiscountValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountValue.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountValue proto.InternalMessageInfo

func (m *DiscountValue) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func (m *DiscountValue) GetValueInCents() int32 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

type DiscountRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountRequest) Reset()         { *m = DiscountRequest{} }
func (m *DiscountRequest) String() string { return proto.CompactTextString(m) }
func (*DiscountRequest) ProtoMessage()    {}
func (*DiscountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa949c85a716cb, []int{3}
}

func (m *DiscountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountRequest.Unmarshal(m, b)
}
func (m *DiscountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountRequest.Marshal(b, m, deterministic)
}
func (m *DiscountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountRequest.Merge(m, src)
}
func (m *DiscountRequest) XXX_Size() int {
	return xxx_messageInfo_DiscountRequest.Size(m)
}
func (m *DiscountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountRequest proto.InternalMessageInfo

func (m *DiscountRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DiscountRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DiscountResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountResponse) Reset()         { *m = DiscountResponse{} }
func (m *DiscountResponse) String() string { return proto.CompactTextString(m) }
func (*DiscountResponse) ProtoMessage()    {}
func (*DiscountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa949c85a716cb, []int{4}
}

func (m *DiscountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountResponse.Unmarshal(m, b)
}
func (m *DiscountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountResponse.Marshal(b, m, deterministic)
}
func (m *DiscountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountResponse.Merge(m, src)
}
func (m *DiscountResponse) XXX_Size() int {
	return xxx_messageInfo_DiscountResponse.Size(m)
}
func (m *DiscountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountResponse proto.InternalMessageInfo

func (m *DiscountResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "hashtest.Product")
	proto.RegisterType((*User)(nil), "hashtest.User")
	proto.RegisterType((*DiscountValue)(nil), "hashtest.DiscountValue")
	proto.RegisterType((*DiscountRequest)(nil), "hashtest.DiscountRequest")
	proto.RegisterType((*DiscountResponse)(nil), "hashtest.DiscountResponse")
}

func init() { proto.RegisterFile("hashtest.proto", fileDescriptor_4caa949c85a716cb) }

var fileDescriptor_4caa949c85a716cb = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x6b, 0xa3, 0x40,
	0x14, 0xc5, 0x57, 0x93, 0x6c, 0xf4, 0xba, 0x71, 0xb3, 0xc3, 0xc2, 0xba, 0x59, 0x16, 0x64, 0xe8,
	0x43, 0xa0, 0x90, 0x07, 0xf3, 0x01, 0x4a, 0xff, 0x40, 0xdb, 0x97, 0xb6, 0x0c, 0x6d, 0x5f, 0xc5,
	0xe8, 0x84, 0x0c, 0x18, 0x9d, 0xce, 0x5c, 0x03, 0xfd, 0x4e, 0xfd, 0x90, 0xc5, 0xf1, 0x4f, 0x52,
	0x52, 0xe8, 0x9b, 0x73, 0xce, 0xf5, 0xf8, 0x9b, 0x73, 0x05, 0x7f, 0x93, 0xe8, 0x0d, 0x72, 0x8d,
	0x0b, 0xa9, 0x4a, 0x2c, 0x89, 0xd3, 0x9d, 0xe9, 0x9b, 0x05, 0xe3, 0x07, 0x55, 0x66, 0x55, 0x8a,
	0xc4, 0x07, 0x5b, 0x64, 0x81, 0x15, 0x5a, 0x73, 0x97, 0xd9, 0x22, 0x23, 0x27, 0xe0, 0x4b, 0x25,
	0x52, 0x1e, 0x8b, 0x22, 0x4e, 0x79, 0x81, 0x3a, 0xb0, 0x43, 0x6b, 0x3e, 0x62, 0x3f, 0x8c, 0x7a,
	0x5b, 0x5c, 0xd6, 0x1a, 0xf9, 0x0d, 0x23, 0x14, 0x98, 0xf3, 0x60, 0x60, 0x5e, 0x6c, 0x0e, 0x24,
	0x04, 0x2f, 0xe3, 0x3a, 0x55, 0x42, 0xa2, 0x28, 0x8b, 0x60, 0x68, 0xbc, 0x43, 0x89, 0x2c, 0xc1,
	0xc9, 0x84, 0x4e, 0xcb, 0xaa, 0xc0, 0x60, 0x14, 0x5a, 0x73, 0x2f, 0xfa, 0xb3, 0xe8, 0x31, 0xaf,
	0x5a, 0xe7, 0x39, 0xc9, 0x2b, 0xce, 0xfa, 0x41, 0xba, 0x83, 0xe1, 0x93, 0xe6, 0xea, 0x08, 0xf5,
	0x3f, 0xc0, 0x5a, 0x28, 0x8d, 0x71, 0x91, 0x6c, 0xb9, 0xc1, 0x74, 0x99, 0x6b, 0x94, 0xbb, 0x64,
	0xcb, 0xc9, 0x3f, 0x70, 0xf3, 0xa4, 0x73, 0x1b, 0x4e, 0xa7, 0x16, 0x8c, 0x49, 0x61, 0x92, 0x25,
	0xc8, 0xe3, 0x72, 0x1d, 0xaf, 0x84, 0xc2, 0x4d, 0x0f, 0x9b, 0x20, 0xbf, 0x5f, 0x5f, 0xd4, 0x12,
	0xbd, 0x86, 0xc9, 0x07, 0x24, 0x32, 0x85, 0x81, 0x4c, 0xd1, 0x10, 0xd8, 0xac, 0x7e, 0xac, 0xdb,
	0xda, 0xd5, 0xd6, 0x51, 0x5b, 0x46, 0x6d, 0xdb, 0xa2, 0x2b, 0xf8, 0xd9, 0x05, 0x31, 0xfe, 0x52,
	0x71, 0x8d, 0x84, 0xc2, 0xb0, 0xd2, 0x5c, 0x99, 0x2c, 0x2f, 0xf2, 0xf7, 0x25, 0xd4, 0x37, 0x65,
	0xc6, 0x23, 0xa7, 0x30, 0x96, 0xcd, 0x96, 0x4c, 0xaa, 0x17, 0xfd, 0xda, 0x8f, 0xb5, 0xeb, 0x63,
	0xdd, 0x04, 0x3d, 0x83, 0xe9, 0xfe, 0x1b, 0x5a, 0x96, 0x85, 0xe6, 0x87, 0x01, 0xd6, 0x57, 0x01,
	0xd1, 0x23, 0x38, 0x5d, 0x00, 0xb9, 0x81, 0xc9, 0xb9, 0x94, 0xf9, 0x6b, 0x2f, 0xfc, 0x3d, 0xde,
	0x52, 0x7b, 0x93, 0xd9, 0xec, 0x33, 0xab, 0x01, 0xa0, 0xdf, 0x56, 0xdf, 0xcd, 0xbf, 0xb7, 0x7c,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x50, 0x97, 0x35, 0xc5, 0x8d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountClient is the client API for Discount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountClient interface {
	ApplyDiscount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountResponse, error)
}

type discountClient struct {
	cc *grpc.ClientConn
}

func NewDiscountClient(cc *grpc.ClientConn) DiscountClient {
	return &discountClient{cc}
}

func (c *discountClient) ApplyDiscount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountResponse, error) {
	out := new(DiscountResponse)
	err := c.cc.Invoke(ctx, "/hashtest.Discount/ApplyDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServer is the server API for Discount service.
type DiscountServer interface {
	ApplyDiscount(context.Context, *DiscountRequest) (*DiscountResponse, error)
}

func RegisterDiscountServer(s *grpc.Server, srv DiscountServer) {
	s.RegisterService(&_Discount_serviceDesc, srv)
}

func _Discount_ApplyDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServer).ApplyDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashtest.Discount/ApplyDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServer).ApplyDiscount(ctx, req.(*DiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashtest.Discount",
	HandlerType: (*DiscountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyDiscount",
			Handler:    _Discount_ApplyDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashtest.proto",
}
