# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashtest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hashtest.proto',
  package='hashtest',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ehashtest.proto\x12\x08hashtest\"|\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0eprice_in_cents\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12)\n\x08\x64iscount\x18\x05 \x01(\x0b\x32\x17.hashtest.DiscountValue\"P\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x15\n\rdate_of_birth\x18\x04 \x01(\t\"4\n\rDiscountValue\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x05\"S\n\x0f\x44iscountRequest\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.hashtest.User\x12\"\n\x07product\x18\x02 \x01(\x0b\x32\x11.hashtest.Product\"6\n\x10\x44iscountResponse\x12\"\n\x07product\x18\x01 \x01(\x0b\x32\x11.hashtest.Product2T\n\x08\x44iscount\x12H\n\rApplyDiscount\x12\x19.hashtest.DiscountRequest\x1a\x1a.hashtest.DiscountResponse\"\x00\x62\x06proto3')
)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='hashtest.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hashtest.Product.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_in_cents', full_name='hashtest.Product.price_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='hashtest.Product.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hashtest.Product.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discount', full_name='hashtest.Product.discount', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=152,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='hashtest.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hashtest.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='hashtest.User.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='hashtest.User.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='hashtest.User.date_of_birth', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=234,
)


_DISCOUNTVALUE = _descriptor.Descriptor(
  name='DiscountValue',
  full_name='hashtest.DiscountValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='hashtest.DiscountValue.pct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='hashtest.DiscountValue.value_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=288,
)


_DISCOUNTREQUEST = _descriptor.Descriptor(
  name='DiscountRequest',
  full_name='hashtest.DiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='hashtest.DiscountRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='hashtest.DiscountRequest.product', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=373,
)


_DISCOUNTRESPONSE = _descriptor.Descriptor(
  name='DiscountResponse',
  full_name='hashtest.DiscountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='hashtest.DiscountResponse.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=429,
)

_PRODUCT.fields_by_name['discount'].message_type = _DISCOUNTVALUE
_DISCOUNTREQUEST.fields_by_name['user'].message_type = _USER
_DISCOUNTREQUEST.fields_by_name['product'].message_type = _PRODUCT
_DISCOUNTRESPONSE.fields_by_name['product'].message_type = _PRODUCT
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['DiscountValue'] = _DISCOUNTVALUE
DESCRIPTOR.message_types_by_name['DiscountRequest'] = _DISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['DiscountResponse'] = _DISCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'hashtest_pb2'
  # @@protoc_insertion_point(class_scope:hashtest.Product)
  ))
_sym_db.RegisterMessage(Product)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'hashtest_pb2'
  # @@protoc_insertion_point(class_scope:hashtest.User)
  ))
_sym_db.RegisterMessage(User)

DiscountValue = _reflection.GeneratedProtocolMessageType('DiscountValue', (_message.Message,), dict(
  DESCRIPTOR = _DISCOUNTVALUE,
  __module__ = 'hashtest_pb2'
  # @@protoc_insertion_point(class_scope:hashtest.DiscountValue)
  ))
_sym_db.RegisterMessage(DiscountValue)

DiscountRequest = _reflection.GeneratedProtocolMessageType('DiscountRequest', (_message.Message,), dict(
  DESCRIPTOR = _DISCOUNTREQUEST,
  __module__ = 'hashtest_pb2'
  # @@protoc_insertion_point(class_scope:hashtest.DiscountRequest)
  ))
_sym_db.RegisterMessage(DiscountRequest)

DiscountResponse = _reflection.GeneratedProtocolMessageType('DiscountResponse', (_message.Message,), dict(
  DESCRIPTOR = _DISCOUNTRESPONSE,
  __module__ = 'hashtest_pb2'
  # @@protoc_insertion_point(class_scope:hashtest.DiscountResponse)
  ))
_sym_db.RegisterMessage(DiscountResponse)



_DISCOUNT = _descriptor.ServiceDescriptor(
  name='Discount',
  full_name='hashtest.Discount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplyDiscount',
    full_name='hashtest.Discount.ApplyDiscount',
    index=0,
    containing_service=None,
    input_type=_DISCOUNTREQUEST,
    output_type=_DISCOUNTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNT)

DESCRIPTOR.services_by_name['Discount'] = _DISCOUNT

# @@protoc_insertion_point(module_scope)
